version: '3.8'

services:
  # Mock EHR Service
  mock-ehr:
    build:
      context: ./mock-ehr
      dockerfile: Dockerfile
    container_name: mock-ehr-server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - donor-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Apache Camel Middleware
  camel-middleware:
    build:
      context: ./camel
      dockerfile: Dockerfile
    container_name: camel-donor-middleware
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EHR_BASE_URL=http://mock-ehr:3001
      - JAVA_OPTS=-Xmx512m -Xms256m
    networks:
      - donor-network
    depends_on:
      mock-ehr:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

networks:
  donor-network:
    driver: bridge
    name: donor-management-network-2

volumes:
  # Optional: Add volumes for logs if needed
  camel-logs:
    driver: local
  ehr-logs:
    driver: local