# ACME Agent Configuration File
# =============================
# This configuration file provides default values for the ECA-ACME agent.
# All values can be overridden by environment variables (see comments below).
# The agent validates this configuration against the JSON schema at:
# config/agent_config_schema.json

# PKI Server Configuration
# ---------------------
# ACME Certificate Authority configuration with multi-environment support.
# The agent automatically detects environment based on ACME_ENVIRONMENT variable.
#
# Supported environments:
#   - development (dev): Local testing with relaxed validation
#   - staging: Pre-production testing with production-like constraints
#   - production (prod): Live environment with strict validation
#
# Environment variable override: <prefix>ACME_ENVIRONMENT (e.g., ACME_ENVIRONMENT)
# Default: development
environment: "development"

# PKI Server URLs by Environment
# -----------------------------
# Base URLs for step-ca ACME server API endpoints by environment.
# These can be overridden per-environment using environment variables:
#   - <prefix>PKI_URL_DEV (e.g., ACME_PKI_URL_DEV)
#   - <prefix>PKI_URL_STAGING (e.g., ACME_PKI_URL_STAGING)
#   - <prefix>PKI_URL_PROD (e.g., ACME_PKI_URL_PROD)
#
# If no environment-specific override is set, falls back to PKI_URL.
pki_environments:
  development:
    url: "https://pki:9000"
    skip_certificate_check: true
    timeout_seconds: 30
  staging:
    url: "https://pki-staging.example.com:9000"
    skip_certificate_check: false
    timeout_seconds: 60
  production:
    url: "https://pki.example.com:9000"
    skip_certificate_check: false
    timeout_seconds: 120

# Fallback PKI URL (used if no environment-specific URL set)
# Environment variable override: <prefix>PKI_URL (e.g., ACME_PKI_URL)
pki_url: "https://pki:9000"

# Certificate Output Path
# ------------------------
# Absolute filesystem path where the agent will write the issued certificate.
# Format: PEM-encoded X.509 certificate with full chain.
# The agent will set file permissions to 0644 (world-readable).
# Parent directory must exist and be writable by the agent.
# In Docker deployments, this typically points to a shared volume.
# Environment variable override: <prefix>CERT_PATH (e.g., ACME_CERT_PATH)
cert_path: "/certs/server/server.crt"

# Private Key Output Path
# ------------------------
# Absolute filesystem path where the agent will write the private key.
# Format: PEM-encoded PKCS#8 format (RSA-2048 or ECDSA P-256).
# The agent will automatically set file permissions to 0600 (owner read/write only).
# SECURITY WARNING: Never transmit this file over the network or expose it.
# Parent directory must exist and be writable by the agent.
# Environment variable override: <prefix>KEY_PATH (e.g., ACME_KEY_PATH)
key_path: "/certs/server/server.key"

# Domain Name
# -----------
# The domain name or hostname to request in the certificate.
# This value will be used as both the Subject Common Name (CN) and
# Subject Alternative Name (SAN) in the certificate request.
# The ACME CA will validate this domain via HTTP-01 challenge, so the
# agent must be reachable at http://{domain_name}/.well-known/acme-challenge/
# Environment variable override: <prefix>DOMAIN_NAME (e.g., ACME_DOMAIN_NAME)
domain_name: "target-server"

# Renewal Threshold Percentage
# -----------------------------
# Trigger certificate renewal when this percentage of the certificate's
# lifetime has elapsed. This provides a safety margin before expiration.
# Value range: 1-100
# Default: 75 (renew at 75% lifetime = 25% remaining)
#
# Examples:
#   - For a 10-minute certificate: 75% triggers renewal after 7.5 minutes
#   - For a 90-day certificate: 75% triggers renewal after 67.5 days
#
# Recommended values:
#   - Short-lived certs (minutes/hours): 70-80 (narrower margin acceptable)
#   - Long-lived certs (days/months): 75-85 (more safety margin)
#
# Environment variable override: <prefix>RENEWAL_THRESHOLD_PCT
renewal_threshold_pct: 75

# Check Interval (seconds)
# -------------------------
# Time to sleep between certificate expiration status checks.
# Lower values = faster detection of approaching expiration, higher resource usage.
# Higher values = reduced CPU/log usage, slower detection.
# Default: 60 seconds
#
# Recommended values based on certificate lifetime:
#   - Certificates lasting minutes: 10-30 seconds
#   - Certificates lasting hours: 60-300 seconds
#   - Certificates lasting days: 300-3600 seconds
#
# Environment variable override: <prefix>CHECK_INTERVAL_SEC
check_interval_sec: 60

# ACME Challenge Directory
# -------------------------
# Base directory where HTTP-01 challenge tokens are placed for CA validation.
# The ACME CA will attempt to fetch challenge tokens from:
#   http://{domain_name}/.well-known/acme-challenge/{token}
#
# This directory must be:
#   - Writable by the agent
#   - Served by the target web server (typically NGINX)
#   - Mounted as a shared volume in Docker deployments
#
# The agent will automatically create the .well-known/acme-challenge subdirectory
# structure if it doesn't exist.
#
# Default: /challenge
# Environment variable override: <prefix>CHALLENGE_DIRECTORY (e.g., ACME_CHALLENGE_DIRECTORY)
challenge_directory: "/challenge"

# Posh-ACME State Directory
# -------------------------
# Posh-ACME stores account and order state in the directory pointed to the
# POSHACME_HOME environment variable. When running via docker compose this
# is set automatically to `/posh-acme-state`, which is backed by a persistent
# volume. The agent falls back to `/config/poshacme` if the environment
# variable is not provided.

# Notes on Additional Configuration
# ----------------------------------
# The following values are HARDCODED in the agent modules and cannot be
# configured via this file or environment variables:
#
# - ACME Provisioner Name: "acme" (hardcoded for step-ca)
#   This is the step-ca provisioner name used for ACME protocol.
#
# - Target Service Name: "target-server" (hardcoded in ServiceReloadController.psm1)
#   This is the Docker container name for the NGINX service to reload.
#
# These values match the Docker Compose deployment architecture and should
# not need modification for standard deployments. If you need to change them,
# you must modify the corresponding PowerShell module source code.

# =============================================================================
# CRL (Certificate Revocation List) Configuration
# =============================================================================
# CRL validation settings for certificate revocation checking
crl:
  # Enable CRL validation checks
  enabled: true

  # URL to download CRL from (step-ca CRL endpoint)
  url: "http://pki:9001/crl/ca.crl"

  # Local cache path for downloaded CRL
  cache_path: "/tmp/ca.crl"

  # Maximum age of cached CRL before re-download (hours)
  max_age_hours: 2.0

  # Check certificates against CRL before renewal
  check_before_renewal: true

# =============================================================================
# Certificate Chain Management Configuration
# =============================================================================
# Certificate chain handling and validation settings
certificate_chain:
  # Enable full certificate chain handling (leaf + intermediates + root)
  enabled: true

  # Certificate chain output path (full chain including intermediates)
  # Environment variable override: <prefix>CERT_CHAIN_PATH (e.g., ACME_CERT_CHAIN_PATH)
  full_chain_path: "/certs/server/server-fullchain.crt"

  # Intermediate certificates output path
  # Environment variable override: <prefix>INTERMEDIATES_PATH (e.g., ACME_INTERMEDIATES_PATH)
  intermediates_path: "/certs/server/server-intermediates.crt"

  # Chain validation options
  validation:
    # Validate certificate chain completeness before installation
    validate_completeness: true

    # Verify chain signatures are valid
    verify_signatures: true

    # Check for expired certificates in the chain
    check_expiry: true

    # Maximum chain depth allowed (prevents certificate chain loops)
    max_depth: 5

  # Chain installation preferences
  installation:
    # Install full chain to cert_path (recommended for NGINX)
    install_full_chain_to_cert_path: true

    # Install leaf-only certificate (for legacy applications)
    install_leaf_only: false

    # Create separate chain files for debugging
    create_separate_chain_files: true

    # Set file permissions for chain files
    chain_file_permissions: "0644"
