services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    # We mount the entire config folder into /vault/config
    volumes:
      - ./vault.hcl:/vault/config/vault.hcl
      - ./certs:/vault/config/certs
      - vault-file:/vault/file
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      # Optional, but recommended, so Vault knows how it should refer to itself
      VAULT_API_ADDR: "https://localhost:8200"
    command: >
      vault server -config=/vault/config/vault.hcl

volumes:
  vault-file:
